trigger:
- none

pool: Prabhas-Agent-Pools

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_parent'
    backendServiceArm: 'Prabha-SC'
    backendAzureRmResourceGroupName: 'rg-rama'
    backendAzureRmStorageAccountName: 'krishnastg5678'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'prod.terraform.tfstate'
