trigger: none
pool: Prabhas-Agent-Pools


parameters:
  - name: doStep1
    type: boolean
    default: true
  - name: doStep2
    type: boolean
    default: false

steps:
- script: echo "Step 1 chal raha hai"
  displayName: Step 1
  condition: eq('${{ parameters.doStep1 }}', true)

- script: echo "Step 2 chal raha hai"
  displayName: Step 2
  condition: eq('${{ parameters.doStep2 }}', true)
