trigger: none
pool: Prabhas-Agent-Pools

steps:
- task: TerraformInstaller@1
  displayName: Terraform Install 
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)todoapp_parent'
    backendServiceArm: 'PrabhaSC-WIF'
    backendAzureRmResourceGroupName: 'rg-rama'
    backendAzureRmStorageAccountName: 'krishnastg5678'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'prod.terraform.tfstate'

# - task: TerraformTask@5
#   displayName: Terraform Validate
#   inputs:
#     provider: 'azurerm'
#     command: 'validate'
#     workingDirectory: '$(System.DefaultWorkingDirectory)todoapp_parent'

# - task: TerraformTask@5
#   displayName: Terraform Plan
#   inputs:
#     provider: 'azurerm'
#     command: 'plan'
#     workingDirectory: '$(System.DefaultWorkingDirectory)todoapp_parent'
#     environmentServiceNameAzureRM: 'PrabhaSC-WIF'



